# Generated by Django 3.2 on 2022-03-23 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=10, verbose_name='계좌 종류(예금, 적금)')),
                ('default_limit_onetime', models.IntegerField(verbose_name=' 1회 출금한도')),
                ('default_limit_oneday', models.IntegerField(verbose_name='1일 출금한도')),
            ],
            options={
                'verbose_name': '계좌 종류',
                'verbose_name_plural': '계좌 종류',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100, unique=True, verbose_name='고유 uuid')),
                ('bank_code', models.CharField(max_length=5, verbose_name='은행 코드')),
                ('account_number', models.CharField(max_length=20, verbose_name='계좌번호')),
                ('amount', models.IntegerField(default=0, verbose_name='총 보유액')),
                ('is_active', models.BooleanField(default=True, verbose_name='계좌 유효성')),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bank.bankaccounttype', verbose_name='계좌 종류')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='회원 아이디')),
            ],
            options={
                'verbose_name': '계좌정보',
                'verbose_name_plural': '계좌정보',
            },
        ),
        migrations.CreateModel(
            name='AccountTransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sended_label', models.CharField(max_length=20, verbose_name='보낼 때 작성할 문구')),
                ('received_label', models.CharField(max_length=20, verbose_name='받을 때 작성할 문구')),
                ('amount', models.IntegerField(verbose_name='송금액')),
                ('fee', models.IntegerField(verbose_name='수수료')),
                ('reg_date', models.DateField(auto_now_add=True, verbose_name='송금 날짜')),
                ('receiver_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver_account', to='bank.bankaccount', verbose_name='수신 계좌번호')),
                ('sender_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender_account', to='bank.bankaccount', verbose_name='발신 계좌번호')),
            ],
            options={
                'verbose_name': '이체 내역',
                'verbose_name_plural': '이체 내역',
            },
        ),
    ]
