# Generated by Django 3.2.7 on 2021-11-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211109_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
